### ISSUE TITLE
[Suggestion] Kondense should not use clusterrole on its serviceaccount

### ISSUE THREAD

**Issue by btwseeu78** [unagex/kondense#21]
Hi,

I just came across your repo, first its really a nice addition hope it grows more.

But i am not sure why we are using a cluster role for this,even in examples i see cluster role. not sure why a controller using sidecar need clusterrole since it will always be namespace scoped.

**Comment by MathieuCesbron** [comment]
Thanks for the idea. You are right, it is unnecessary, I will update the `ClusterRole` to `Role`.

**Comment by MathieuCesbron** [comment]
Done 👍 Thanks again for the suggestion !
